# Ignore everything by default
- ignore: {}

##### Baked-in warnings

# TODO: https://github.com/ndmitchell/hlint/issues/748
# - modules:
#   - {name: [Data.Set, Data.HashSet], as: Set} # if you import Data.Set qualified, it must be as 'Set'
#   - {name: [Data.List], as: List}
#   - {name: [Data.Sequence], as: Seq}

- warning: {name: Evaluate}
- warning: {name: Redundant $!}
- warning: {name: Redundant /=}
- warning: {name: Redundant as}
- warning: {name: Redundant fromInteger}
- warning: {name: Redundant fromIntegral}
- warning: {name: Redundant if}
- warning: {name: Redundant not}
- warning: {name: Redundant negate}
- warning: {name: Redundant pair}
- warning: {name: Redundant seq}
- warning: {name: Use concatMap}
- warning: {name: Use fewer LANGUAGE pragmas}
- warning: {name: Use when}

# TODO: Fix all intances an enable me :-)
# - warning: {name: Use newtype instead of data}

##### Custom warnings

- package:
    name: what4
    modules:
    - import What4.Interface

- group:
    name: what4
    enabled: true
    imports:
    - package what4
    rules:
    - warning:
        name: "Use andAllOf"
        lhs: foldM (andPred s) (truePred s)
        rhs: andAllOf s folded
    - warning: {name: "Use andAllOf"}

    - warning:
        name: "Use orOneOf"
        lhs: foldM (orPred s) (falsePred s)
        rhs: orOneOf s folded
    - warning: {name: "Use orOneOf"}

    - warning:
        name: "Use realToNat"
        lhs: integerToNat s =<< realToInteger s r
        rhs: realToNat s r
    - warning:
        name: "Use realToNat"
        lhs: realToInteger s r >>= integerToNat s
        rhs: realToNat s r
    - warning: {name: "Use realToNat"}
    - ignore: {name: "Use realToNat", within: [What4.Interface]} # defined here

    - warning:
        name: "Use maxUnsignedBV"
        lhs: bvLit s w (maxUnsigned w)
        rhs: maxUnsignedBV s w
    - warning: {name: "Use maxUnsignedBV"}
    - ignore: {name: "Use maxUnsignedBV", within: [What4.Interface]} # defined here

    - warning:
        name: "Use maxSignedBV"
        lhs: bvLit s w (maxUnsigned w)
        rhs: maxUnsignedBV s w
    - warning: {name: "Use maxSignedBV"}
    - ignore: {name: "Use maxSignedBV", within: [What4.Interface]} # defined here

    - warning:
        name: "Use falsePred"
        lhs: notPred s (falsePred s)
        rhs: truePred s
    - warning: {name: "Use falsePred"}

    - warning:
        name: "Use truePred"
        lhs: notPred s (truePred s)
        rhs: falsePred s
    - warning: {name: "Use truePred"}


# TODO: Fix all intances an enable me :-)
# - warning:
#     name: "Use 'panic'"
#     lhs: "warning"
#     rhs: 'panic "nameOfFunction" ["more lines of details"]'
# - warning: {name: "Use 'panic'"}
