dist: xenial
sudo: false

language: c

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal

git:
  submodules: true

matrix:
  include:
    - env: CABALVER="2.4" GHCVER="8.6.3"
      compiler: ": #GHC 8.6.3"
      addons:
        apt:
          sources: [hvr-ghc]
          packages:
            - libglpk-dev # blt
            - libntl-dev # blt
            - libboost-all-dev
            - cabal-install-2.4
            - ghc-8.6.3

    - env: CABALVER="2.4" GHCVER="8.4.3"
      compiler: ": #GHC 8.4.3"
      addons:
        apt:
          sources: [hvr-ghc]
          packages:
            - libglpk-dev # blt
            - libntl-dev # blt
            - libboost-all-dev
            - cabal-install-2.4
            - ghc-8.4.3

    - os: osx
      env: CABALVER="2.4" GHCVER="8.6.3"
      compiler: ": #GHC 8.6.3"

before_install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]];
    then
        brew update;
        brew install ghc;
        brew install cabal-install;
    fi
  - unset CC
  - export PATH=/opt/ghc/bin:$HOME/.cabal/bin:$PATH

script:
  - cabal update
  - cabal new-build all -j --disable-optimization --allow-newer
